site_name: Mini Pi plus From Scratch
site_description: Complete guide for learning Mini Pi plus robot from scratch
site_url: http://127.0.0.1:8082/pi-plus-from-scratch/
repo_url: https://github.com/Ajilan292/pi-plus-from-scratch
repo_name: Ajilan292/pi-plus-from-scratch
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/ht-logo-trademark.png
  favicon: assets/ht-logo-trademark.png
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Home:
      - Home: index.html
      - Get Started: get-started.md

  - Tutorials:
      - Tutorials: tutorials/intro/index.md
      - First Run: tutorials/first-run/index.md
      - Setup: tutorials/setup/index.md
      - Safety & Teleoperation: tutorials/safety-and-teleop/index.md
      - Bringup: tutorials/bringup/index.md
      - Simulation Basics: tutorials/sim-basics/index.md
      - Sim2Real Deployment: tutorials/sim2real-deploy/index.md
      - Troubleshooting: tutorials/troubleshooting/index.md

  - Reference:
      - Reference: reference/index.md
      - Hardware: reference/hardware/index.md
      - Software: reference/software/index.md
      - Interfaces: reference/interfaces/index.md
      - Configuration: reference/configuration/index.md

  - Explanation:
      - Sim2Real Theory: explanation/sim2real.md
      - Design Principles: explanation/design-principles.md

  - Changelogs:
      - Releases: changelogs/releases.md
